Repository open-rpc/examples, pull requests merged in 2019-03, with the labels that each got.

#34 Add dependabot badge to README
  README.md
Labels: LGTM

#36 fix: update petstore expanded name
  service-descriptions/petstore-expanded-openrpc.json
Labels: bug

#43 fix: add type object to Pet in petstore
  package.json
  service-descriptions/petstore-openrpc.json
Labels: bug

#45 fix: rename pet to newPet for create_pet method
  package.json
  service-descriptions/petstore-expanded-openrpc.json
Labels: bug

#46 fix: must include object type
  package.json
  service-descriptions/petstore-expanded-openrpc.json
Labels: bug

#50 Feat/typescript
  .editorconfig
  .gitignore
  index.js
  jest.config.js
  package-lock.json
  package.json
  src/index.test.ts
  src/index.ts
  test.js
  tsconfig.json
  tsfmt.json
  tslint.json
Labels: enhancement

#52 feat: add semantic-release stuff
  .circleci/config.yml
  README.md
Labels: enhancement

#54 fix: change workflow name
  .circleci/config.yml
Labels: bug

#55 Fix/circle cache
  .circleci/config.yml
  package.json
Labels: bug

#56 fix: add releaserc
  .releaserc
Labels: bug

#59 fix: build before releasing
  .circleci/config.yml
Labels: bug

#57 fix: upgrade the config
  .circleci/config.yml
Labels: enhancement

#58 feat: add protbot
  .github/stale.yml
Labels: enhancement

#62 fix: unique param names in method
  service-descriptions/simple-math-openrpc.json
Labels: bug

#64 fix: dependabot should run in ci
  .circleci/config.yml
Labels: bug

#66 fix: still needs the component for integer
  service-descriptions/simple-math-openrpc.json
Labels: bug

#69 fix: broken test
  package-lock.json
  package.json
  src/index.test.ts
Labels: bug

#74 fix: use type null
  service-descriptions/petstore-openrpc.json
Labels: bug

#80 fix: add variables to simple math
  service-descriptions/simple-math-openrpc.json
Labels: bug

#78 fix: add links to simplemath
  service-descriptions/simple-math-openrpc.json
Labels: bug

#76 fix: fill out link example
  service-descriptions/link-example-openrpc.json
Labels: bug

#85 fix: schema is required
  service-descriptions/link-example-openrpc.json
  service-descriptions/params-by-name-petstore-openrpc.json
Labels: bug

#87 fix(petstoreExpanded): missing schema in result
  service-descriptions/petstore-expanded-openrpc.json
Labels: bug

#84 fix: petstore create pet needs params
  service-descriptions/petstore-openrpc.json
Labels: bug
